<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ujamii_geocoder"
 *
 * Auto generated by Extension Builder 2018-03-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Geocoder Toolkit',
    'description' => 'Connecting http://geocoder-php.org/Geocoder with TYPO3 DataHandler API',
    'category' => 'services',
    'author' => 'Michael Grundkötter',
    'author_email' => 'mg@ujamii.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
